version: '3.8'
services:
  postgres-dev:
    image: postgres:16.2
    environment:
      POSTGRES_DB: bank
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
    ports:
      - "5434:5432"

  rabbitmq-dev:
    image: rabbitmq:3-management
    ports:
      - "15673:15672"
      - "5673:5672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  app:
    build:
      context: .
      target: application
      args:
        SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8080:8080"
    depends_on:
      - postgres-dev
      - rabbitmq-dev
    environment:
      SPRING_PROFILES_ACTIVE: dev
