version: '3.8'
services:
  postgres-test:
    image: postgres:16.2
    environment:
      POSTGRES_DB: bank
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5432:5432"

  rabbitmq-test:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  app-test:
    build:
      context: .
      target: build-test
      args:
        SPRING_PROFILES_ACTIVE: test
    depends_on:
      - postgres-test
      - rabbitmq-test
    environment:
      SPRING_PROFILES_ACTIVE: test
