spring:
  datasource:
    url: jdbc:postgresql://postgres-test:5432/bank
    username: testuser
    password: testpass
  rabbitmq:
    host: rabbitmq-test
    port: 5672
    username: user
    password: password
